services:
  - type: web
    name: accsmarket-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.main
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: src/main.py

